{
  "formatVersion": "1.1",
  "component": {
    "group": "com.reblaze.sdk",
    "module": "mobile-sdk",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 959890,
          "sha512": "c5c47fa73689a3587867094e5bf8e4577eab2fdf8809dbcd9a5066d221fb1b099d1e9c70f242514ddb705d41a76a755b3e5099a37d0cc132491128ef4284e11e",
          "sha256": "65855bf0a22e82a08e23981541b4119e05b5d4908ede9e4712c2dffccf4155f3",
          "sha1": "c6644966416ad23126f6d520f9da55bfb223ef06",
          "md5": "0d6adfbe2ed7a09658781aab9c1c14db"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 959890,
          "sha512": "c5c47fa73689a3587867094e5bf8e4577eab2fdf8809dbcd9a5066d221fb1b099d1e9c70f242514ddb705d41a76a755b3e5099a37d0cc132491128ef4284e11e",
          "sha256": "65855bf0a22e82a08e23981541b4119e05b5d4908ede9e4712c2dffccf4155f3",
          "sha1": "c6644966416ad23126f6d520f9da55bfb223ef06",
          "md5": "0d6adfbe2ed7a09658781aab9c1c14db"
        }
      ]
    }
  ]
}
