{
  "formatVersion": "1.1",
  "component": {
    "group": "com.reblaze.sdk",
    "module": "mobile-sdk",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 952912,
          "sha512": "65c0a1b4a5c42862d6374e9556d177425e65d4ebb6d413b7e6b689a3c553e7b8172c55f332b11fa80b3d1fbe2426b3a8a111ae73496d16675cd3b724bbf5b863",
          "sha256": "f1d7a5d753609c3377d861dc19911f2a922cdb38b17a91c9cb6dd86bcf7de3f2",
          "sha1": "22a35eafedc24015cf3a9b8b4c56d09bd0ffbd9b",
          "md5": "0d8955fd663402e712f38b737d20ab94"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 952912,
          "sha512": "65c0a1b4a5c42862d6374e9556d177425e65d4ebb6d413b7e6b689a3c553e7b8172c55f332b11fa80b3d1fbe2426b3a8a111ae73496d16675cd3b724bbf5b863",
          "sha256": "f1d7a5d753609c3377d861dc19911f2a922cdb38b17a91c9cb6dd86bcf7de3f2",
          "sha1": "22a35eafedc24015cf3a9b8b4c56d09bd0ffbd9b",
          "md5": "0d8955fd663402e712f38b737d20ab94"
        }
      ]
    }
  ]
}
