{
  "formatVersion": "1.1",
  "component": {
    "group": "com.reblaze.sdk",
    "module": "mobile-sdk",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 960540,
          "sha512": "cd8e38ee77bc1b5cd7145ff7f402de61cde3b2ffc89d9c0cb4b60d79a245750526ff2e1ee9f2e086e4af4fd4abb7a2793d5b94d32d39cae54b6598aed9ddc481",
          "sha256": "9fd0836b51ea6fa532a6fab89af7b7fea64c1cf77cc6128f895fec9bee138f3c",
          "sha1": "80b5480a2408f27b521aed6774d6f154b7dd1348",
          "md5": "715777f785cb0aafe30d4aa7704bd7b3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.0.aar",
          "url": "mobile-sdk-2.0.aar",
          "size": 960540,
          "sha512": "cd8e38ee77bc1b5cd7145ff7f402de61cde3b2ffc89d9c0cb4b60d79a245750526ff2e1ee9f2e086e4af4fd4abb7a2793d5b94d32d39cae54b6598aed9ddc481",
          "sha256": "9fd0836b51ea6fa532a6fab89af7b7fea64c1cf77cc6128f895fec9bee138f3c",
          "sha1": "80b5480a2408f27b521aed6774d6f154b7dd1348",
          "md5": "715777f785cb0aafe30d4aa7704bd7b3"
        }
      ]
    }
  ]
}
